---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
  namespace: default
data:
  test-script.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      vus: 500, // Number of virtual users
      duration: '120s', // Test duration
    };

    export default function () {
      let res = http.get('http://ui.ui.svc/home');
      check(res, {
        'status is 200': (r) => r.status === 200,
      });
      sleep(1);
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: k6-load-test
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: k6
    image: grafana/k6:latest
    command: ["k6", "run", "/scripts/test-script.js"]
    volumeMounts:
    - name: k6-script-volume
      mountPath: /scripts
  volumes:
  - name: k6-script-volume
    configMap:
      name: k6-script
